# Generated by Django 5.1.4 on 2025-02-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_fees_payment_method_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='fees',
            name='take_by',
            field=models.CharField(default='Admin', max_length=30),
        ),
    ]
