# Generated by Django 5.1.4 on 2025-02-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0006_attendence'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
